#!/bin/bash

if [ $(id -u) -ne 0 ] ; then
    printf "you must be a superuser.\n" >&2
    exit 1
elif [ "$(uname -i)" != 'armvl7' ] ; then
    printf "not an armvl7 platform.\n" >&2
    exit 2
fi

download_dir="$(pwd)"
gz_file="swift-3.0-2016-08-16-RPi23-ubuntu16.04.tar.gz"
install_dir="/opt/swift/swift-3.0"

wget "http://swift-arm.ddns.net/job/Swift-3.0-Pi3-ARM-Incremental/41/artifact/$gz_file"

[ ! -d "$install_dir" ] && mkdir --parents "$install_dir"
cd "$install_dir" && tar -xzf "$download_dir/$gz_file"

apt-get update

apt-get install -y libicu-dev clang-3.6

update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.6 100
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.6 100

exit 0
