#!/bin/bash -x

if [ $(id -u) -ne 0 ] ; then
    printf "you must be a superuser!!!\n" >&2
    exit 1
fi

url="https://github.com/apple/swift/raw/master/utils"
install_dir="$(dirname "$(whereis swift | awk '{print $2}')")"
[ -z "$install_dir" ] && install_dir="/opt/swift/swift-3.0/swift-3.0-RELEASE-ubuntu14.04/usr/bin"

if [ -z "$install_dir" -o "$install_dir" = '.' -o ! -d "$install_dir" ] ; then
    printf "unable to determine swift installation directory!!!\n" >&2
    exit 2
fi

for fname in "gyb" \
             "gyb.py"
do
    if [ ! -f "$install_dir/$fname" ] ; then
        wget "$url/$fname"
        mv "$fname" "$install_dir"
    fi
done

chmod 755 "$install_dir/gyb"

cat << @@ >"$install_dir/gyb-source"
#!/bin/bash

gyb_extension=".gyb"

for gyb_file in \$(find "." -name "*$gyb_extension" | sort)
do
    src_file="\$(printf "%s/%s" "\$(dirname "\$gyb_file")" "\$(basename "\$gyb_file" "\$gyb_extension")")"

    if [ "\$gyb_file" -nt "\$src_file" ] ; then
        printf "%s -> %s\n" "\$gyb_file" "\$src_file" >&1

        gyb --line-directive '' -o "\$src_file" "\$gyb_file"
    fi
done

exit 0
@@

chmod 755 "$install_dir/gyb-source"

exit 0
